version: "3"
services:
  php:
    container_name: "tarefa_DW_2A"
    image: php:8.1.16-apache
    volumes:
     - ./codigos:/var/www/html/
    ports:
     - 8080:80      
  db:
    image: mariadb:10.5
    container_name: "tarefa"
    restart: always
    environment:
    - MARIADB_USER=root
    - MARIADB_ROOT_PASSWORD=54321
  adminer:
    image: adminer:4.8.1
    container_name: "adminer_tarefa"
    restart: always
    ports:
      - 90:8080
